services:
  apache:
    build: .
    #container_name: crm_app
    ports:
      - "8081:80"
   # volumes:
   #   - /var/www/html/crm:/var/www/html
   # restart: always
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      APP_ENV: production
      APP_DEBUG: "false"

  mysql:
    image: mysql:8.0
    #container_name: crm_mysql
    #restart: always
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: crm
      MYSQL_USER: emri
      MYSQL_PASSWORD: Fuel1234@
      #MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3309:3306"
    volumes:
      - crm_db:/var/lib/mysql

volumes:
  crm_db:
